### ISSUE TITLE
Default shortcut 0 annoying

### ISSUE THREAD

**Issue by wilfm** [leonardo-bartoli/gnome-shell-extension-Recents#1]
Thanks for this extension (nice advanced to alternative one :), but I noticed after installing that `0` suddenly became the key to open the Recent menu. I disabled this in settings but its quite annoying as a default setting.

So could [the default setting](https://github.com/leonardo-bartoli/gnome-shell-extension-Recents/blob/master/schemas/org.gnome.shell.extensions.recents.gschema.xml#L5):

``` xml
    <default><![CDATA[['0']]]></default>
```

become `['']`, `Disabled` or something please?

**Comment by leonardo-bartoli** [comment]
Fixed, in 2eb42e7169a4395d74676fd62c87503a2cffa95d

Thanks
