### ISSUE TITLE
Adding sticky (pinned) items

### ISSUE THREAD

**Issue by iliaross** [leonardo-bartoli/gnome-shell-extension-Recents#11]
Please be kind adding ability to pin and always keep at the top certain items. That would be very useful.

**Comment by chorus12** [comment]
Thumbs up for that functionality!

**Comment by ragundo** [comment]
Yes, please!!!!!

**Comment by leonardo-bartoli** [comment]
Surely the next feature to add

**Comment by iliaross** [comment]
Thank you very much. Besides, if possible, make them sortable.

**Comment by miguelsan** [comment]
A similar functionality is present for [Clipboard Indicator](https://extensions.gnome.org/extension/779/clipboard-indicator/), perhaps you could get some ideas from there @leonardo-bartoli?
