### ISSUE TITLE
Position option for left of application menu

### ISSUE THREAD

**Issue by dag** [leonardo-bartoli/gnome-shell-extension-Recents#14]
For me the most natural position of this extension would be between Activities and the application menu. I use the Places status indicator extension and it looks weird when the application menu is between Places and Recent—I'd like it to be "Activities Places⏷ Recent⏷ Firefox⏷" for example. Any chance you could add an option for that?

**Comment by tkhai** [comment]
I have the same issue. On left position the order becomes:
[Applications][Places][Application settings][Recent]

which looks very strange.

To place [Recent] before [Application settings] I had to replace  -1 with 1 in extension.js:
    Main.panel.addToStatusArea('recents', new Indicator.RecentsIndicator(settings), position == 'right' ? 0 : 1, position);

Please, consider to make configure option for this or another defaults.
