### ISSUE TITLE
Exclude deleted files

### ISSUE THREAD

**Issue by dag** [leonardo-bartoli/gnome-shell-extension-Recents#15]
Would be useful if this extension didn't list files in Recent that have been deleted, and can't be opened.

**Comment by mathdesc** [comment]
Hello,
I've mirrored on [my forked repo](https://github.com/mathdesc/gnome-shell-extension-Recents) and add the feature which does exclusion on pattern matching on private folders because gnome recents doesn't provide this feature. This is a bit hacky but maybe that give you any insights ?
