### ISSUE TITLE
Migrate to Gnome gitlab

### ISSUE THREAD

**Issue by ElectricPrism** [leonardo-bartoli/gnome-shell-extension-Recents#17]
Seeing as how long time Linux competitor Microsoft is acquiring GitHub and Gnome has official tooling that offers parallel features to GitHub -- please consider migrating this project to http://gitlab.gnome.org || www.gitlab.com or the equivalent.

**Comment by leonardo-bartoli** [comment]
Good idea, I'm going to do it as soon as possible
