### ISSUE TITLE
[Gnome 3.32] Seems to have stopped working; had been fine since your last update.

### ISSUE THREAD

**Issue by businessBoris** [leonardo-bartoli/gnome-shell-extension-Recents#19]
Error message of "TypeError: this._construct is not a function".
OS: Fedora 30 Beta, but have seen another has noticed difficulties too - listed on https://extensions.gnome.org/extension/977/recent-items/

I'm sure you're busy so any pointers would be appreciated.

**Comment by Sidethorn** [comment]
Hello, no news yet?

**Comment by leonardo-bartoli** [comment]
I try to port to the latest version of gnome in the coming days

**Comment by Sidethorn** [comment]
Grazie 😉

**Comment by Sidethorn** [comment]
hello maybe this could help to speed up things for you 
https://gitlab.gnome.org/GNOME/gnome-shell/issues/1069

**Comment by leonardo-bartoli** [comment]
Should work now.
I'm going to publish a new version on e.g.o. later

**Comment by Sidethorn** [comment]
Thanks

**Comment by businessBoris** [comment]
Just a quick thank-you @leonardo-bartoli; it's already being offered on the e.g.o site.
I'm sure that it's my most actively used extension;' the other one is not quite as good because it's on the RHS only - yours is movable.

**Comment by MostFrabjous** [comment]
It's not working here - ?!
* Removed the extension (and checked `.local/share/gnome-shell/extensions/` for any leftovers)
* Reinstalled the extension from [extensions.gnome.org](https://extensions.gnome.org/extension/977/recent-items/)
* Loading extension failes with `Recents_leonardo.bartoli.gmail.com has error: TypeError: this._construct is not a function` : (
