### ISSUE TITLE
no search, or focus search text in manjaro gnome 3.34

### ISSUE THREAD

**Issue by pablingas** [leonardo-bartoli/gnome-shell-extension-Recents#23]

**Comment by rvtb** [comment]
I have the same issue on Ubuntu 19.10 on gnome-shell 3.34.1.
When I enter a text to search, nothing happens. The list of recent files does not change.

I just test the git version, and it works.
However, the version on extension.gnome.org is not yet updated.

**Comment by leonardo-bartoli** [comment]
I was waiting for some feedback, I'm going to post a new version in the coming days

**Comment by rvtb** [comment]
Thank you for your response.
For me this issue is resolved in the git version.

And thank you for this very useful extension.

**Comment by arakan94** [comment]
Hello, the search in extension.gnome.org version isn't working for me (Fedora 32, GNOME 3.36).. Perhaps it needs another update?
