### ISSUE TITLE
Gnome 3.20

### ISSUE THREAD

**Issue by forteller** [leonardo-bartoli/gnome-shell-extension-Recents#4]
This is a real life saver! Please update it to work with Gnome 3.20! Thank you so much! :)

**Comment by leonardo-bartoli** [comment]
I should be able to upload a new version on e.g.o by Monday, I'm going to close this issue as soon as the new version is available.

**Comment by chorus12** [comment]
We are lost without this extention... Please update. Thank you!!!

**Comment by chorus12** [comment]
It is fixed in git - need to do a manual install. Thank you!!!

**Comment by leonardo-bartoli** [comment]
Sorry I had been quite busy lately.
As chorus12 said the git version should work with 3.20, however I finally managed to upload the extension on g.e.o
