### ISSUE TITLE
Preferences window won't run with GNOME 3.24

### ISSUE THREAD

**Issue by jbicha** [leonardo-bartoli/gnome-shell-extension-Recents#6]
I installed this extension at random today on Ubuntu GNOME 17.04 with GNOME 3.24. Its preference window won't load.

Note that GNOME is now using mozjs38 which has stricter syntax.

**Comment by Sadi58** [comment]
And here's the error message I get:
```
Error: Requiring St, version none: Typelib file for namespace 'Clutter', version '0' not found
Stack trace:
  @/home/sadi/.local/share/gnome-shell/extensions/Recents@leonardo.bartoli.gmail.com/prefs.js:6:7
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
```

**Comment by leonardo-bartoli** [comment]
Should be fixed in bfc88f8568675f2159639e2585d46c89eb8aa469

**Comment by michael-reichert** [comment]
I installed the extension a few days ago, via extensions.gnome.org. I am also using Ubuntu GNOME 17.04.
Still, the preferences won't load. Is it expected to work now? is the fix included in the version available from extensions.gnome.org?

**Comment by leonardo-bartoli** [comment]
The fix is currently present only on the git version. I had been quite busy lately, only today I was able to upload an updates version of the extension on e.g.o, should be available from there in a couple of days.

**Comment by leonardo-bartoli** [comment]
An updated version should be available now from  from extensions.gnome.org

**Comment by michael-reichert** [comment]
Works fine now. Thanks!
