### ISSUE TITLE
Allow Drag'n'Drop to applications

### ISSUE THREAD

**Issue by mammuth** [leonardo-bartoli/gnome-shell-extension-Recents#7]
Is it possible to allow the user to drag a file from the list into another application?

That'd be super cool! :+1: :sunglasses:

**Comment by Mofef** [comment]
I would like that a lot!
Use case: you make a screenshot and want to drag the result onto a document to insert it or onto an IM to share it.

**Comment by leonardo-bartoli** [comment]
I'm going to look into this issue during summer holidays

**Comment by mammuth** [comment]
@Mofef Yep, your use case is exactly what made me opening this issue! :blush:

Looking forward to it @leonardo-bartoli ! :tada:
