### ISSUE TITLE
Inconsistent Left Positioning

### ISSUE THREAD

**Issue by ElectricPrism** [leonardo-bartoli/gnome-shell-extension-Recents#8]
When starting Gnome Recent menu is positioned here:

![screenshot from 2017-07-04 23-30-48](https://user-images.githubusercontent.com/635971/27851701-d018d6f4-6110-11e7-8536-62fd617fe488.png)

After some use, resolution changes, etc... it moves to the right of the Dash to Panel dock.

![screenshot from 2017-07-04 23-28-49](https://user-images.githubusercontent.com/635971/27851676-b68350a2-6110-11e7-8fbe-3cd003965569.png)

I think the alignment code is wonky, I suggest looking at the Places official alignment code to see how Gnome does it to make sure when set to left it stays in one place.

Thank you :+1:  :)

**Comment by leonardo-bartoli** [comment]
The indicators positioning in gnome is generally a little wonky ;)
If I remember correctly the Places indicator looks for the existence of a 'app-menu' and position itself absolutely into the panel using an index. This can cause some problem cause indicator position is initialization order dependent.
So in conclusion there is not a nice way to solve this problem, perhaps we can try to look for 'places' and set the position accordingly, but I'm not sure this will fix the problem.

**Comment by lorendias** [comment]
This issue seems to be fixed with this patch:
https://github.com/leonardo-bartoli/gnome-shell-extension-Recents/pull/12

**Comment by leonardo-bartoli** [comment]
Thanks seems fine
